//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDiscountJoin
    {
        public UserDiscountJoin()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int UserDiscountJoinId { get; set; }
        public int UserId { get; set; }
        public int UserDiscountId { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual UserDiscount UserDiscount { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
