//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseballCard
    {
        public BaseballCard()
        {
            this.BaseballCardTransactions = new HashSet<BaseballCardTransaction>();
            this.StoreInventories = new HashSet<StoreInventory>();
        }
    
        public int BaseballCardId { get; set; }
        public string Player { get; set; }
        public string Team { get; set; }
        public decimal Cost { get; set; }
    
        public virtual ICollection<BaseballCardTransaction> BaseballCardTransactions { get; set; }
        public virtual ICollection<StoreInventory> StoreInventories { get; set; }
    }
}
