//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseballCardTransaction
    {
        public int BaseballCardTransactionId { get; set; }
        public int BaseballCardId { get; set; }
        public int TransactionId { get; set; }
        public int Quantity { get; set; }
        public decimal Cost { get; set; }
        public virtual BaseballCard BaseballCard { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
