//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PracticeGDVPEntities : DbContext
    {
        public PracticeGDVPEntities()
            : base("name=PracticeGDVPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaseballCard> BaseballCards { get; set; }
        public DbSet<BaseballCardTransaction> BaseballCardTransactions { get; set; }
        public DbSet<RuleSet> RuleSets { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<StoreInventory> StoreInventories { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<UserDiscount> UserDiscounts { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
