//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleSet
    {
        public int RuleSetId { get; set; }
        public string Name { get; set; }
        public int MajorVersion { get; set; }
        public int MinorVersion { get; set; }
        public string RuleSet1 { get; set; }
        public Nullable<short> Status { get; set; }
        public string AssemblyPath { get; set; }
        public string ActivityName { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
