//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.StoreInventories = new HashSet<StoreInventory>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int StoreId { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public decimal DiscountRate { get; set; }
    
        public virtual User UserTable { get; set; }
        public virtual ICollection<StoreInventory> StoreInventories { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
